Screen:

    FloatLayout:
        MDLabel:
            id: WelcomeLabel_Patient
            text: "Welcome!"
            font_size: 40
            halign: 'center'
            size_hint_y: None
            pos_hint: {"top": .9, "center_x": .5}
            height: self.texture_size[1]

        MDTextFieldRound:
            id: User_Patient
            hint_text: "Patient Username"
            icon_right: "account"
            font_size: 25
            size_hint: .7, .06
            pos_hint: {"top":0.8, "center_x": 0.5}

        MDTextFieldRound:
            id: Password_Patient
            hint_text: "Password"
            icon_right: "eye-off"
            size_hint_x: None
            font_size: 25
            size_hint: .7, .06
            pos_hint: {"top":0.7, "center_x": 0.5}
            password: True

        MDRoundFlatButton:
            text: "LOG IN"
            font_size: 25
            size_hint: .4, .06
            pos_hint: {"top":0.6, "center_x": 0.5}
            # on_press: app.logger()         

        Widget:
            size_hint_y: None
            height: 10