<FirebaseLoginScreen>:
    background: ""
    canvas.before:
        Rectangle:
            size: self.size
            pos: self.pos
            source: root.background
    on_email_exists:
        sign_up_screen.ids.sign_in_button.disabled = False
        sign_up_screen.ids.sign_in_button.opacity = 1

    on_email_not_found:
        sign_in_screen.ids.sign_in_button.disabled = False
        sign_in_screen.ids.sign_in_button.opacity = 1

    ScreenManager:
        id: screen_manager
        WelcomeScreen:
            id: Welcome_Screen
            name: "Welcome_Screen"
        LogInDoctor:
            id: LogIn_Doctor
            name: "LogInScreen_Doctor"
        LogInPatient:
            id: LogIn_Patient
            name: "LogInScreen_Patient"