<FirebaseLoginScreen>:

    ScreenManager:
        id: screen_manager

        Welcome_Page:
            id: Welcome_Page
            name: "Welcome_Page"
        
        Firebase_LoginScreen_Doctor:
            id: firebase_login_screen_doctor
            name: "firebase_login_screen_doctor"
            
    
        Firebase_LoginScreen_Patient:
            id: firebase_login_screen_patient
            name: "firebase_login_screen_patient"
            